name: minio-shared
director_uuid: d43a09bc-1291-497d-a04d-1b66d883a9b8
releases:
  - {name: minio-shared-boshrelease, version: latest}
stemcells:
  - alias: bosh-google-kvm-ubuntu-trusty-go_agent
    os: ubuntu-trusty
    version: latest

instance_groups:
  - name: minio-shared
    instances: 1
    azs: [us-central1-a]
    jobs:
    - name: minio-service-broker
      release: minio-shared-boshrelease
    properties:
     credential:
      user: minio
      password: minio123
    vm_type: xlarge.disk
    cloud_properties:
      tags:
      - allow-ssh
    stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
    persistent_disk_type: '307200'
    networks:
      - name: ert

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
